repos:
- repo: local
  hooks:
    - id: pylint
      name: pylint
      entry: python3.8 -m pylint
      language: system
      types: [python]
      exclude: "(tests/.*)|(examples/.*)"
      args: [
          "-rn", # Only display messages
          "-sn", # Don't display the score
        ]

